# Generated by Django 6.0.3 on 2026-04-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='available_slots',
            field=models.IntegerField(default=0),
        ),
    ]
