# Generated by Django 6.0.3 on 2026-04-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.FloatField(default=0.0),
        ),
    ]
