# Generated by Django 6.0.3 on 2026-04-09 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_alter_booking_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='parking',
            name='available_slots',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('user', 'Parking User'), ('provider', 'Parking Provider')], default='user', max_length=10),
        ),
    ]
