# Generated by Django 6.0.3 on 2026-04-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_booking_vehicle_type_alter_booking_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='vehicle_number',
            field=models.CharField(default='UP32 AB 1234', max_length=20),
            preserve_default=False,
        ),
    ]
