# Generated by Django 6.0.3 on 2026-04-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0007_booking_vehicle_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='vehicle_type',
            field=models.CharField(choices=[('Bike', 'Bike'), ('Car', 'Car'), ('SUV', 'SUV'), ('Truck', 'Truck')], max_length=20),
        ),
    ]
