# Generated by Django 6.0.3 on 2026-04-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0008_alter_booking_total_price_alter_booking_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
