# Generated by Django 6.0.3 on 2026-04-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0009_booking_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parking',
            name='available_slots',
        ),
        migrations.RemoveField(
            model_name='parking',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='parking',
            name='price_per_hour',
        ),
        migrations.RemoveField(
            model_name='parking',
            name='total_slots',
        ),
        migrations.AddField(
            model_name='parking',
            name='available_bike_slots',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parking',
            name='available_car_slots',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parking',
            name='available_suv_slots',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parking',
            name='available_truck_slots',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parking',
            name='bike_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='parking',
            name='bike_slots',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parking',
            name='car_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='parking',
            name='car_slots',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parking',
            name='suv_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='parking',
            name='suv_slots',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parking',
            name='truck_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='parking',
            name='truck_slots',
            field=models.IntegerField(default=0),
        ),
    ]
