# Generated by Django 6.0.3 on 2026-04-14 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0010_remove_parking_available_slots_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parking',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
