# Generated by Django 6.0.3 on 2026-04-16 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0011_parking_latitude_parking_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_code',
            field=models.CharField(default='SP-3F-A12', editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ParkingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='parking_gallery/')),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='parking.parking')),
            ],
        ),
    ]
