# Generated by Django 6.0.3 on 2026-04-16 22:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0014_booking_is_active_alter_booking_id_alter_parking_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parking',
            name='image',
        ),
        migrations.AddField(
            model_name='parking',
            name='daily_free_slots',
            field=models.IntegerField(default=0, help_text='Number of free slots available daily'),
        ),
        migrations.AddField(
            model_name='parking',
            name='discount_percentage',
            field=models.FloatField(default=0, help_text='Discount percentage for paid slots (e.g., 50 for 50% off)'),
        ),
        migrations.AddField(
            model_name='parking',
            name='first_free_limit',
            field=models.IntegerField(default=0, help_text='Number of first bookings that get free slots'),
        ),
        migrations.AddField(
            model_name='parking',
            name='last_reset_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parking',
            name='used_first_free_today',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parking',
            name='used_free_slots_today',
            field=models.IntegerField(default=0),
        ),
    ]
