# Generated by Django 5.2.7 on 2026-04-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0017_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_timing',
            field=models.CharField(choices=[('pay_now', 'Pay Now'), ('pay_at_end', 'Pay at End')], default='pay_now', max_length=15),
        ),
        migrations.AddField(
            model_name='parking',
            name='qr_code_image',
            field=models.ImageField(blank=True, help_text='Upload your UPI/Payment QR code', null=True, upload_to='qr_codes/'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('qr_code', 'QR Code Payment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_method',
            field=models.CharField(choices=[('qr_code', 'QR Code Payment')], max_length=20),
        ),
    ]
