# Generated by Django 6.0.3 on 2026-04-18 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0018_booking_payment_timing_parking_qr_code_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parking',
            old_name='used_first_free_today',
            new_name='bike_first_free_limit',
        ),
        migrations.RenameField(
            model_name='parking',
            old_name='used_free_slots_today',
            new_name='bike_free_slots',
        ),
        migrations.RemoveField(
            model_name='parking',
            name='daily_free_slots',
        ),
        migrations.RemoveField(
            model_name='parking',
            name='first_free_limit',
        ),
        migrations.RemoveField(
            model_name='parking',
            name='last_reset_date',
        ),
        migrations.AddField(
            model_name='parking',
            name='car_first_free_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parking',
            name='car_free_slots',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parking',
            name='suv_first_free_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parking',
            name='suv_free_slots',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parking',
            name='truck_first_free_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parking',
            name='truck_free_slots',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parking',
            name='used_bike_first_free_today',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parking',
            name='used_bike_free_today',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parking',
            name='used_car_first_free_today',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parking',
            name='used_car_free_today',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parking',
            name='used_suv_first_free_today',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parking',
            name='used_suv_free_today',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parking',
            name='used_truck_first_free_today',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parking',
            name='used_truck_free_today',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='parking',
            name='discount_percentage',
            field=models.FloatField(default=0),
        ),
    ]
