# Generated by Django 6.0.3 on 2026-04-20 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0019_rename_used_first_free_today_parking_bike_first_free_limit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parking',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='parking',
            name='used_bike_first_free_today',
        ),
        migrations.RemoveField(
            model_name='parking',
            name='used_bike_free_today',
        ),
        migrations.RemoveField(
            model_name='parking',
            name='used_car_first_free_today',
        ),
        migrations.RemoveField(
            model_name='parking',
            name='used_car_free_today',
        ),
        migrations.RemoveField(
            model_name='parking',
            name='used_suv_first_free_today',
        ),
        migrations.RemoveField(
            model_name='parking',
            name='used_suv_free_today',
        ),
        migrations.RemoveField(
            model_name='parking',
            name='used_truck_first_free_today',
        ),
        migrations.RemoveField(
            model_name='parking',
            name='used_truck_free_today',
        ),
    ]
