# Generated by Django 6.0.3 on 2026-04-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0020_remove_parking_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='last_reset_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parking',
            name='used_bike_first_free_today',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parking',
            name='used_bike_free_today',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parking',
            name='used_car_first_free_today',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parking',
            name='used_car_free_today',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parking',
            name='used_suv_first_free_today',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parking',
            name='used_suv_free_today',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parking',
            name='used_truck_first_free_today',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parking',
            name='used_truck_free_today',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='parking',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
