# Generated by Django 6.0.3 on 2026-04-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0021_parking_last_reset_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='amount',
            field=models.IntegerField(default=30000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipt',
            name='payment_status',
            field=models.CharField(default='SUCCESS', max_length=20),
        ),
    ]
