# Generated by Django 6.0.3 on 2026-04-20 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0022_receipt_amount_receipt_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='pdf_file',
        ),
    ]
