# Generated by Django 5.2.7 on 2026-04-24 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0023_remove_receipt_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='actual_exit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_checked_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='overstay_penalty',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('active', 'Active'), ('overstaying', 'Overstaying'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='booked', max_length=20),
        ),
    ]
