# Generated by Django 5.2.7 on 2026-04-24 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0025_payment_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parking',
            name='qr_code_image',
        ),
    ]
