# Generated by Django 5.2.7 on 2026-04-24 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0026_remove_parking_qr_code_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
