# Generated by Django 5.2.7 on 2026-04-26 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0027_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='assigned_slot',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
