# Generated by Django 5.2.7 on 2026-04-26 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0028_booking_assigned_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
